# Generated by Django 2.0.3 on 2018-05-12 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20180512_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='url_type',
            field=models.SmallIntegerField(choices=[(1, 'alias'), (2, 'abslute_url')], default=2),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tags',
            field=models.ManyToManyField(blank=True, to='crm.Tag'),
        ),
    ]
