# Generated by Django 2.0.3 on 2018-05-15 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_auto_20180515_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id_num',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='证件号'),
        ),
    ]
